vnda/vnda-tracker

app/assets/stylesheets/custom.scss
app/views/layouts/application.html.erb
app/views/shops/index.html.erb
app/views/trackings/_form.html.erb
app/views/trackings/edit.html.erb
app/views/trackings/index.html.erb
app/views/trackings/new.html.erb
app/views/trackings/show.html.erb
config/initializers/locale.rb
config/locales/pt-BR.yml

https://trello.com/c/KvIGoLKp/5780-sugest%C3%B5es-melhorias-tracker

update bootstrap and others visual tweaks

---

.gitignore
.rubocop.yml
app/controllers/trackings_controller.rb
app/models/carrier.rb
app/models/tracking.rb
app/views/trackings/index.html.erb
spec/rails_helper.rb
spec/requests/trakings/index_spec.rb

https://trello.com/c/KvIGoLKp/5780-sugest%C3%B5es-melhorias-tracker

make it possible filter trackings by status

---

app/models/tracking.rb
app/models/tracking_notification.rb
app/workers/notify.rb
db/migrate/20180615210156_create_tracking_notifications.rb
db/schema.rb
spec/workers/notify_spec.rb

https://trello.com/c/KvIGoLKp/5780-sugest%C3%B5es-melhorias-tracker

store notifications history

---

app/models/tracking.rb
app/models/tracking_event.rb
app/services/correios.rb
app/services/postmon.rb
app/views/trackings/show.html.erb
db/migrate/20180611220128_create_tracking_events.rb
spec/models/tracking_event_spec.rb
spec/models/tracking_spec.rb
spec/services/correios_spec.rb
spec/services/postmon_spec.rb

https://trello.com/c/KvIGoLKp/5780-sugest%C3%B5es-melhorias-tracker

store all status changes of tracking codes

---

app/views/shops/_form.html.erb

https://trello.com/c/QqL20kTu/5680-status-de-pedido-entregue

add a tip on notification url field

---

app/models/carrier.rb
app/services/correios_html.rb
spec/fixtures/correios-with-events.html
spec/fixtures/correios-without-events.html
spec/models/carrier_spec.rb
spec/services/correios_html_spec.rb

https://trello.com/c/UiYDm76V/6162-portal-postal-pedidos-n%C3%A3o-est%C3%A3o-tendo-seu-status-alterado-para-enviado

get tracking data from Correios as HTML

---

app/services/jadlog.rb
spec/services/jadlog_spec.rb

https://trello.com/c/M1apT6Wi/6647-jadlog-trabalhar-url-de-tracking

use shipmentId to query tracking status of jadlog2

---

app/services/jadlog.rb
spec/services/jadlog_spec.rb

prevent error with unexpected Jadlog response

---

app/models/carrier.rb
app/services/mandae.rb
app/services/tnt.rb
app/services/total_express/base.rb
app/views/shops/_form.html.erb
config/locales/pt-BR.yml
db/migrate/20190417135630_add_mandae_fileds_to_shops.rb
db/schema.rb
spec/models/carrier_spec.rb
spec/services/jadlog_spec.rb
spec/services/mandae_spec.rb

track Mandaê deliveries

---

app/controllers/trackings_controller.rb
app/views/shared/_flash.html.erb
app/views/shops/edit.html.erb
app/views/shops/index.html.erb
app/views/shops/show.html.erb
app/views/trackings/edit.html.erb
app/views/trackings/index.html.erb
app/views/trackings/show.html.erb

add breadcrumb to get better navigation

---

app/services/correios_html.rb
spec/services/correios_html_spec.rb

Update Correios tracking url

---

app/views/layouts/application.html.erb
app/views/trackings/_form.html.erb
app/views/trackings/index.html.erb
app/views/trackings/show.html.erb
config/locales/pt-BR.yml
spec/services/correios_html_spec.rb
spec/services/intelipost_spec.rb
spec/services/postmon_spec.rb

add translation and icon for delivery status

---

app/workers/refresh_tracking_status.rb
spec/workers/refresh_tracking_status_spec.rb

reduce update interval for orders with out of delivery status

---

app/services/carrier_url.rb
spec/services/carrier_url_spec.rb

fill tracking url for Mandaê

---

app/services/correios_html.rb
spec/services/correios_html_spec.rb

parse event date with time zone

---

app/assets/stylesheets/_helpers.scss
app/views/layouts/application.html.erb

fix broken logo

---

app/models/carrier.rb
app/models/tracking.rb
app/models/tracking_event.rb
app/services/correios.rb
app/services/correios_html.rb
app/services/intelipost.rb
app/services/jadlog.rb
app/services/mandae.rb
app/services/postmon.rb
app/services/tnt.rb
app/services/total_express/tracker.rb
spec/models/tracking_event_spec.rb
spec/models/tracking_spec.rb
spec/services/correios_html_spec.rb
spec/services/correios_spec.rb
spec/services/intelipost_spec.rb
spec/services/jadlog_spec.rb
spec/services/mandae_spec.rb
spec/services/postmon_spec.rb

register all events of tracking

---

app/assets/stylesheets/_helpers.scss
app/controllers/search_controller.rb
app/models/shop.rb
app/views/layouts/public.html.erb
app/views/search/show.html.erb
config/locales/pt-BR.yml
config/routes.rb
db/migrate/20190621141243_add_slug_to_shops.rb
db/schema.rb
spec/models/shop_spec.rb
spec/requests/search/show_spec.rb

tracking events public list

---

app/controllers/intelipost_controller.rb
app/models/carrier.rb
app/models/tracking.rb
app/services/carrier_url.rb
config/routes.rb
spec/models/tracking_spec.rb
spec/requests/intelipost/create_spec.rb
spec/services/carrier_url_spec.rb

use intelipost url if tracking code was equal to order code

---

app/models/tracking.rb
spec/models/tracking_spec.rb

remove old Intelipost customization of tracking code

---

app/models/tracking_event.rb

add data to Honeybadger context to better debug

---

app/services/delivery_center.rb
app/views/shops/_form.html.erb
db/migrate/20200102131625_add_delivery_center_to_shops.rb
db/schema.rb
spec/services/delivery_center_spec.rb

integrate with Delivery Center

---

app/views/search/show.html.erb

Sort events by ocurrence

---

app/models/carrier.rb
app/models/tracking.rb
app/services/correios.rb
app/services/correios_html.rb
app/services/delivery_center.rb
app/services/intelipost.rb
app/services/jadlog.rb
app/services/mandae.rb
app/services/postmon.rb
app/services/total_express/tracker.rb
db/migrate/20200106193724_add_last_response_to_trackings.rb
db/schema.rb
spec/models/tracking_spec.rb
spec/services/correios_html_spec.rb
spec/services/correios_spec.rb
spec/services/delivery_center_spec.rb
spec/services/intelipost_spec.rb
spec/services/jadlog_spec.rb
spec/services/mandae_spec.rb
spec/services/postmon_spec.rb

save last API response after do update delivery status

---

app/models/carrier.rb
app/services/correios.rb
app/services/delivery_center.rb
app/services/jadlog.rb
app/services/loggi.rb
app/services/mandae.rb
app/services/tnt.rb
app/services/total_express/tracker.rb
app/views/shops/_form.html.erb
config/locales/pt-BR.yml
db/migrate/20200319153810_add_loggi_to_shops.rb
db/schema.rb
spec/services/loggi_spec.rb

Integração da Loggi para rastreio do pedido. Segue abaixo o link do card no trello.
https://trello.com/c/Fzl6oBix/9138-integra%C3%A7%C3%A3o-loggi-tracker
Nesse PR tentei seguir o padrão de outras integrações, para os mais experientes, peço que olhem com atenção e informe qualquer modificação necessária.

Integração Loggi

---

Gemfile.lock

update rack to fix error on sidekiq web

---

config/routes.rb

avoid error on sidekiq web to access retries and schedules

---

app/services/correios_html.rb

avoid encoding errors

---

app/services/total_express/api.rb
app/services/total_express/status_reader.rb
spec/services/total_express/status_reader_spec.rb

Adiciona cache e trata pedidos com mais de um retorno da api

---

app/views/trackings/index.html.erb

hide schedule button for delivered tracking codes

---

app/models/carrier.rb
app/services/carrier_url.rb
app/services/melhor_envio.rb
app/services/vnda/shop.rb
app/views/shops/_form.html.erb
config/locales/pt-BR.yml
db/migrate/20200921232742_add_melhor_envio_to_shops.rb
db/schema.rb
spec/services/melhor_envio_spec.rb
spec/services/vnda/shop_spec.rb

https://trello.com/c/60gF3QmR
Depende da https://github.com/vnda/vnda-tracker/pull/80

Adiciona integração com o Melhor Envio

---

app/services/jadlog.rb
spec/services/jadlog_spec.rb

Corrige erro de SSL na consulta da Jadlog

---

app/services/total_express/status_reader.rb
spec/services/total_express/status_reader_spec.rb

add 4 to Total Express statuses mapping

---

app/services/correios_html.rb
spec/services/correios_html_spec.rb

Adiciona nova situação no parse em HTML dos Correios

---

app/services/carrier_url.rb
app/services/melhor_envio.rb
spec/services/carrier_url_spec.rb

Adiciona URL de rastreio para o Melhor Envio

---

app/services/correios_html.rb
spec/services/correios_html_spec.rb

Adiciona novo status no parser do Correios

---

app/workers/refresh_tracking_status.rb
spec/workers/refresh_tracking_status_spec.rb

Notifica a api_v2 quando o status "Saiu para entrega" 

---

Gemfile.lock

https://trello.com/c/KDeC23nj/11458-tracking-no-bling
Atualiza versão da gem mimemagic para 0.3.10
Como a versão antiga da gem foi removida do rubygems, os testes envolvendo a nova versão falhavam por não poder instalar a gem.
A versão atualizada da gem instalou tanto localmente quanto no teste automatizado do circleci feito neste PR

Atualização versão da gem mimemagic

---

Gemfile
Gemfile.lock

https://trello.com/c/RFPceawa/12442-bling-ajuste-tracking
Adição da gem Awesome Print
Com essa gem fica muito mais fácil printar na tela arrays, hashs e outros objetos mais complexos durante os testes
Rodando specs, chamando `ap` durante os testes manuais

Adiciona gem awesome print

---

app/services/jadlog.rb
app/views/shops/_form.html.erb
db/migrate/20210511191115_add_jadlog_search_field_to_shops.rb
db/schema.rb
spec/services/jadlog_spec.rb

https://trello.com/c/craPgoPQ/12255-invicta-rastreio

search tracking status by cte on Jadlog
